#!/usr/bin/env python3
"""Freeze the main paper's cross-reference numbers for a standalone excerpt.

An excerpt cites algorithms, equations, theorems and sections that live in the
full paper. Resolving them at build time would make every excerpt build depend on
the main document having been compiled first, and a missing .aux there prints
every one of them as ??. Freezing the numbers keeps the excerpt self-contained.

Two properties are easy to get wrong and both produce ?? in the output:

1. cleveref needs BOTH ``\\newlabel{L}`` and ``\\newlabel{L@cref}``. Extracting only
   the plain label leaves every ``\\cref`` unresolved.
2. The set of labels to freeze must be DISCOVERED from the files the excerpt
   actually builds. A hardcoded list silently goes stale the moment a file is
   added to the excerpt, and the omission surfaces as ?? much later.

Usage
-----
    freeze-xrefs.py --aux main.aux --out excerpt/xrefs-frozen.tex \\
                    --scan excerpt --scan excerpt/tables

Exits non-zero and names the labels if any are absent from the .aux, which
usually means the main document needs rebuilding first.
"""
import argparse
import pathlib
import re
import sys

SKIP_NAMES = {"xrefs-frozen.tex"}

parser = argparse.ArgumentParser()
parser.add_argument("--aux", required=True, help="main document .aux file")
parser.add_argument("--out", required=True, help="generated .tex to write")
parser.add_argument("--scan", action="append", required=True,
                    help="directory of excerpt .tex files; repeatable")
parser.add_argument("--skip", action="append", default=[],
                    help="basename to exclude from scanning; repeatable")
args = parser.parse_args()

aux_path = pathlib.Path(args.aux)
if not aux_path.exists():
    sys.exit(f"{aux_path} missing; build the main document first")

skip = SKIP_NAMES | set(args.skip)
sources = []
for d in args.scan:
    for p in sorted(pathlib.Path(d).glob("*.tex")):
        if p.name not in skip:
            sources.append(p)
if not sources:
    sys.exit("no excerpt sources found; check --scan")

text = "".join(p.read_text(encoding="utf-8") for p in sources)
# Comments never contribute a reference that reaches the PDF.
text = re.sub(r"(?<!\\)%.*", "", text)

used = set(re.findall(r"\\(?:cref|Cref|ref|eqref|autoref)\{([^}]*)\}", text))
# A label the excerpt defines itself must NOT be frozen, or the excerpt would
# print the main document's numbering for its own floats.
local = set(re.findall(r"\\label\{([^}]*)\}", text))
external = sorted(used - local)

aux = aux_path.read_text(encoding="utf-8")
entries, missing = [], []
for label in external:
    for key in (label, label + "@cref"):
        m = re.search(r"^\\newlabel\{" + re.escape(key) + r"\}\{.*\}$", aux, re.M)
        if m:
            entries.append(m.group(0))
        elif key == label:
            missing.append(label)

out = pathlib.Path(args.out)
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(
    "% Generated by freeze-xrefs.py. Do not edit.\n" + "\n".join(entries) + "\n",
    encoding="utf-8")

print(f"scanned {len(sources)} files; froze {len(entries)} entries "
      f"for {len(external)} external labels -> {out}")
if missing:
    sys.exit("absent from " + str(aux_path) + ": " + ", ".join(missing))
